name: Conditional Execution Workflow

on:
  push:
    branches:
      - test1

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate JSON file
        run: |
          echo '{ 
            "Repo1": { 
              "source_system": "Bitbucket", 
              "Bitbucket_Repo": "https://www.bitbucket-dummy.com/project1/repo1", 
              "Migration_story": "https://www.jira-dummy.com/project1/story1", 
              "Migration_wave": "wave1", 
              "Validate_Repo_Migration": "Y", 
              "Validate_Jenkins_Migration": "Y", 
              "Jenkins_Job": { 
                "Jenkins_Job_Path": "https://www.jenkins-dummy.com/project1", 
                "Jenkins_Job_Name": ["CI_Job1", "CI_Job2", "CI_Job3"] 
              } 
            }, 
            "App_Contact": { 
              "email": "ashish@gmail.com", 
              "phone": "555-555-5555" 
            } 
          }' > config.json

      - name: Display JSON file
        run: cat config.json

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v3
        with:
          name: config-json
          path: config.json

      - name: Read JSON and set environment variables
        run: |
          json_file="config.json"
          source_system=$(jq -r '.Repo1.source_system' "$json_file")
          echo "source_system=$source_system" >> $GITHUB_ENV

      - name: Print specific environment variables from JSON
        run: cat $GITHUB_ENV

      - name: Run Bitbucket to GitHub
        
        if: ${{ env.source_system == 'Bitbucket' }}
        run: |
          echo "running bb to gh migration"

      - name: Run Azure DevOps to GitHub migration
        if: ${{ env.source_system == 'AzureDevops' }}
        run: |
          echo "running ado to gh migration"
