name: Config File Workflow

on:
  push:
    branches:
      - test1

jobs:
  generate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate JSON file
        run: >
          echo '{ 
            "Repo": { 
              "source_system": "Bitbucket", 
              "Bitbucket_Repo": "https://www.bitbucket-dummy.com/project1/repo1", 
              "Migration_story": "https://www.jira-dummy.com/project1/story1", 
              "Migration_wave": "wave1", 
              "Validate_Repo_Migration": "Y", 
              "Validate_Jenkins_Migration": "Y", 
              "Jenkins_Job": { 
                "Jenkins_Job_Path": "https://www.jenkins-dummy.com/project1", 
                "Jenkins_Job_Name": ["CI_Job1", "CI_Job2", "CI_Job3"] 
              } 
            }, 
            "App_Contact": { 
              "email": "ashish@gmail.com", 
              "phone": "555-555-5555" 
            } 
          }' > config.json

      - name: Display JSON file
        run: cat config.json

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: config-json
          path: config.json

  master-config:
    needs: generate-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JSON artifact
        uses: actions/download-artifact@v4
        with:
          name: config-json
          path: .

      - name: Display JSON file
        run: cat config.json

      - name: Read JSON and set environment variables
        id: read_json
        run: |
          json_file="config.json"

          jq -r '.Repo | to_entries | .[] | "\(.key)=\(.value)"' "$json_file" | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: run bitbucket to github
        if: env.source_system == 'BitBucket'
        run: |
            echo "running bb to gh migration"

      - name: Display Environment Variables 

        run: | 
         echo "Source System: ${env.source_system}" 
         echo "Bitbucket Repo: ${ env.Bitbucket_Repo }" 

    #   - name: run azure devops to github migartion
    #     run: |
    #       if [ "$source_system" = "AzureDevops" ]; then
    #         echo "running ado to gh migration"
    #       fi

    #   - name: Conditional execution based on source system
    #     run: |
    #       if [ "$source_system" = "AzureDevops" ]; then
    #         echo "running ado to gh migration"
    #       fi


        
