name: Example Workflow

on:
  push:
    branches:
      - csv-reader

jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
      TASK_IDS: "10001,10002,10003"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create CSV with JIRA task IDs
        run: |
          echo "JIRA_TASK_IDS" > jira_task_ids.csv
          for task_id in $(echo $TASK_IDS | tr ',' ' '); do
            echo "$task_id" >> jira_task_ids.csv
          done

      - name: Store CSV content in environment variable
        id: store_csv
        run: |
          JIRA_TASK_IDS=$(cat jira_task_ids.csv | tr '\n' ',')
          echo "JIRA_TASK_IDS=${JIRA_TASK_IDS%,}" >> $GITHUB_ENV

      - name: Display CSV content from environment variable
        run: |
          echo "JIRA_TASK_IDS: $JIRA_TASK_IDS"
