name:  CSV creator

on:
  push:
    branches:
      - csv-reader

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create CSV with JIRA task IDs
        run: |
          echo "JIRA_TASK_IDS" > jira_task_ids.csv
          task_ids="10001,10002,10003"
          for task_id in $(echo $task_ids | tr ',' ' '); do
            echo "$task_id" >> jira_task_ids.csv
          done

      - name: Display CSV content
        run: cat jira_task_ids.csv
