name: Unified Config Workflow

on:
  push:
    branches:
      - dynamic-wf

jobs:
  generate-config:
    runs-on: ubuntu-latest
    outputs:
      source_system: ${{ steps.set-output.outputs.Source_System }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate JSON file
        run: >
          echo '{ 
            "Repo1": { 
              "Source_System": "Bitbucket", 
              "Bitbucket_Repo": "https://www.bitbucket-dummy.com/project1/repo1", 
              "Migration_story": "https://www.jira-dummy.com/project1/story1", 
              "Migration_wave": "wave1", 
              "Validate_Repo_Migration": "Y", 
              "Validate_Jenkins_Migration": "Y", 
              "Jenkins_Job": { 
                "Jenkins_Job_Path": "https://www.jenkins-dummy.com/project1", 
                "Jenkins_Job_Name": ["CI_Job1", "CI_Job2", "CI_Job3"] 
              } 
            }, 
            "App_Contact": { 
              "email": "ashish@gmail.com", 
              "phone": "555-555-5555" 
            } 
          }' > config.json

      - name: Display JSON file
        run: cat config.json
        
      - name: set environment variables
        run: |
          json_file="config.json"
          jq -r '.Repo1 | to_entries[]? | select(.value!=null) | "\(.key)=\(.value)"' "$json_file" | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done
      - name: Read JSON and set environment variables
         echo $Source_System
        run: |
         echo "::set-output name=Source_System::$Source_System"






  master-workflow:
    runs-on: ubuntu-latest
    needs: generate-config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo hello world
        run: |
          echo "Hello, World!"
          echo "Source System: ${{ needs.generate-config.outputs.source_system }}"
