name: Combined Workflow

on:
  push:
    branches:
      - csv-reader

jobs:
  generate-and-use-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Repositories Output
        id: generate_output
        run: |
          echo '{
            "Repo1": { "Source_System": "Bitbucket" },
            "Repo2": { "Source_System": "ado" },
            "Repo3": { "Source_System": "GitHub" }
          }' > output.json
          repos=$(jq -r 'keys | join(",")' output.json)
          echo "::set-output name=repo_list::$repos"

      - name: Parse JSON and Create List
        id: parse
        run: |
          repos=$(jq -r 'keys[]' output.json)
          repo_list=()
          for repo in $repos; do
            source_system=$(jq -r --arg repo "$repo" '.[$repo].Source_System' output.json)
            repo_list+=("$repo:$source_system")
          done
          echo "::set-output name=repo_list::$(printf '%s\n' "${repo_list[@]}" | jq -R . | jq -s .)"

  call-second-job:
    needs: generate-and-use-output
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.generate-and-use-output.outputs.repo_list) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Source System for ${{ matrix.repo }}
        run: |
          IFS=':' read -r repo source_system <<< "${{ matrix.repo }}"
          echo "Running tasks for $repo with Source_System: $source_system"
