name: master orchestation workflow
on:
  workflow_run:
    workflows:
      - Config File Generator
    types:
      - completed
jobs:
  master-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: config.json
          path: .
      - name: Process JSON
        run: |
          cat config.json
